services:
  - type: web
    name: cac-inventory-api
    runtime: node
    buildCommand: npm install && npm run build && npm run setup-db && node scripts/comprehensive-seed-data.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: static
    name: cac-inventory
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://cac-inventory-api.onrender.com/api