services:
  # Backend API service
  - type: web
    name: rainbow-room-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        fromService:
          name: rainbow-room-frontend
          type: web
          property: url
    disk:
      name: data-and-uploads
      mountPath: /data-uploads
      sizeGB: 1

  # Frontend static site
  - type: web
    name: rainbow-room-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

    # Auto-deploy on code changes
    autoDeploy: true